### ISSUE TITLE
Charged Block Producing Bug

### ISSUE THREAD

**Issue by darkshadow543** [T145/ElementalCreepers#14]
So, I was fooling around and ran into this.  Not sure if Inteded.
### Expected Behavior
Charged explosions should be contained by the area they are in.  And should also avoid closed spaces
### Actual Behavior
Charged light creepers and other block producing creepers fill every space by chunk with their block. 

### Steps to Reproduce (including precondition)
Install Epic Mob siege(13.160) and The Lost Cities(2.0.7) mod.  When you spawn in any block producing creeper with an egg, there is a chance it will be charged.  Light a charged creeper with a flint and steel and boom, you now have filled buildings and filled spaces.

### Screenshot of this Problem
![2018-04-22_17 05 09](https://user-images.githubusercontent.com/14943673/39099948-a3cd40a0-4650-11e8-9d72-ba0485354415.png)
![2018-04-22_17 09 59](https://user-images.githubusercontent.com/14943673/39099949-a3db7210-4650-11e8-8880-17dc2742b514.png)
![2018-04-22_17 40 14](https://user-images.githubusercontent.com/14943673/39100189-49f0835e-4654-11e8-8a8f-2e410a774cf8.png)
Excessive webbing from a charged spider creeper.  Maybe it should be more round than cubical?
![2018-04-22_17 45 16](https://user-images.githubusercontent.com/14943673/39100277-6860b0f6-4655-11e8-9ca2-f65c0e46aec6.png)

### Your Environment

- OS: Windows 10
- Minecraft version: 1.12.2
- Elemental Creepers version: 4.3.3.g5616356
- Forge version: 14.23.2.2634

**Comment by T145** [comment]
This is an intended feature. Suggestions on how to improve them or add other cool charged conditions are always welcome!

**Comment by darkshadow543** [comment]
I would say that it is over the top, also, it would be interesting if it were more circular rather than square.
