### ISSUE TITLE
Grass Block head issue

### ISSUE THREAD

**Issue by Rovi23** [T145/ElementalCreepers#15]
I use forge 1.12.2 - 14.23.3.2655 and only ElementarCreepers mod is installed but the creepers of the mod are with a grass block instead of normal head.

I use Windows 10

![2018-04-23_14 09 17](https://user-images.githubusercontent.com/5680890/39125639-edaff302-46ff-11e8-926e-463fdc5fcff1.png)

**Comment by T145** [comment]
This is a feature. On certain holidays the creeper heads will be specific blocks.

[https://github.com/T145/ElementalCreepers/blob/master/src/main/java/T145/elementalcreepers/client/render/entity/layers/LayerFestiveCreeper.java#L49](https://github.com/T145/ElementalCreepers/blob/master/src/main/java/T145/elementalcreepers/client/render/entity/layers/LayerFestiveCreeper.java#L49)
